version: "3.8"
services:
  neo4j:
    image: neo4j:5.12
    container_name: neo4j
    ports:
      - "7474:7474" # browser
      - "7687:7687" # bolt
    environment:
      NEO4J_AUTH: "neo4j/testpassword"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  neo4j_data:
  neo4j_logs:
